### ISSUE TITLE
dark theme の導入

### ISSUE THREAD

**Issue by a24hori** [7ma7X/Typora-Onigiri#1]
たびたびお世話になっております．
本テーマですが，画面エディット用にダークテーマも欲しいのですが，開発可能でしょうか？
自力でやろうとしましたが，どこのパラメータをいじればいいのかわからなかったので，issue として書かせていただきました．
以上，お手数かけますがご返信のほどよろしくお願いいたします．

**Comment by kaisugi** [comment]
かしこまりました。1週間ほどお待ちください 🙇

**Comment by a24hori** [comment]
お願いしちゃって申し訳ないです．ゆっくりお待ちしておりますね！

**Comment by kaisugi** [comment]
@Keith-Campbell 

dark theme を作ってみました。

https://github.com/7ma7X/Typora-Onigiri/blob/feature%23night/typora-theme-onigiri.zip?raw=true

↑このリンクをクリックすると、dark theme を含んだ Onigiri テーマの zip をダウンロードできます。中に入っている `onigiri-night.css` をご確認ください。

**Comment by kaisugi** [comment]
![スクリーンショット 2019-11-03 20 11 53](https://user-images.githubusercontent.com/36184621/68084293-3e390b80-fe77-11e9-9288-2490877b4944.png)

このような見た目になっています。
もし使用してみて、配色に改善点があると感じた場合は、イシューにてお知らせください。

**Comment by a24hori** [comment]
早速作成したいただき，誠にありがとうございます！
これで，とても落ち着いて作業ができるようになります．
自分でも問題を見つけたら適宜報告させていただきますね．
