### ISSUE TITLE
バッククォート内の文字列の表示

### ISSUE THREAD

**Issue by a24hori** [7ma7X/Typora-Onigiri#3]
お世話になっております．
バッククォートで囲まれた文字列の表示ですが，四角い枠で囲まれてしまいます．
![backquote](https://user-images.githubusercontent.com/6898616/69475966-e7d84080-0e16-11ea-875f-e2ff020ebaae.PNG)

枠がないほうが好ましいと思いますので，修正いただけると幸いです．

**Comment by kaisugi** [comment]
承知致しました。

**Comment by kaisugi** [comment]
e10e89317b71d35a770db6526a8d2e344fcb30f8 で対応してみました。
もしまだ直っていなかったら教えてください 🙇

**Comment by a24hori** [comment]
対応誠にありがとうございます．
もう一箇所新たに見つけたのですが，設定画面のボタンの文字色が背景色とかぶっているようです．
こちらも修正していただけると幸いでございます．
![preference](https://user-images.githubusercontent.com/6898616/69491296-a018ee00-0ed6-11ea-8353-2c1d4af4310b.PNG)

**Comment by a24hori** [comment]
もしかすると，使用しているOS（windows）が常時ダークモードであるせいかもしれませんが．

**Comment by kaisugi** [comment]
それはOSの問題というか、Typora本体の問題なのでは、という気がします。
試しに他のダークテーマ（ `Night` など）に切り替えて、その設定画面の表示が変わるかどうかを確認してみてください。

ちなみに私はmacOSを使っていますが、

<img width="812" alt="スクリーンショット 2019-11-24 18 37 08" src="https://user-images.githubusercontent.com/36184621/69492736-7d440500-0ee9-11ea-91cd-ab353fdc2d88.png">

テーマに関わらずこの色のままです。

**Comment by a24hori** [comment]
最新のバージョンで試しました．
他のダークテーマ（`Night`）では以下のように表示されました．
![preference2](https://user-images.githubusercontent.com/6898616/69493900-1e39bc80-0ef8-11ea-88b7-9120f9a5434f.PNG)

投稿された画像

> <img alt="スクリーンショット 2019-11-24 18 37 08" width="812" src="https://user-images.githubusercontent.com/36184621/69492736-7d440500-0ee9-11ea-91cd-ab353fdc2d88.png">

は見た感じ，別ウィンドウで設定画面が表示されていますが，最近のバージョンはエディタ内の画面が切り替わる仕組みになっており，設定画面もテーマに依存するようです．

（以下はテーマ`GIthub`の場合の設定画面です）
![preference3](https://user-images.githubusercontent.com/6898616/69493947-dff0cd00-0ef8-11ea-8325-2f306fa96666.PNG)

**Comment by kaisugi** [comment]
なるほど....

私は最新版のはずですがそうならないので、OSの問題のような気がしてきました。  
大学配布PCがWindowsなので、そちらで今度試してみますね :)

**Comment by a24hori** [comment]
お手数かけます．
よろしくお願いいたします．

**Comment by kaisugi** [comment]
fe174309fd6f9db42817fce90ef4fa3d8ec7d238 にて対応してみました。ご確認お願いいたします。

**Comment by a24hori** [comment]
見やすい表示に変わりました！
ご対応誠にありがとうございました．
